name: Tanglewood
footer_text: Tanglewood
contact_email: tanglewoodindy@gmail.com
dues_amount: '$100 per household'
dues_url: 'https://www.paypal.com/qrcodes/managed/250f1e68-c4a0-42d6-a0c6-76b1653a984f'
dues_check_payable_to: 'Tanglewood Neighborhood Association and deliver them to: Ali Herman 5234 E. 69th Street'
dues_notes: 'PayPal: @tanglewood46220'
facebook_url: 'https://www.facebook.com/profile.php?id=100012393229055'
nextdoor_url: 'https://nextdoor.com/g/rflgc4mej/?utm_campaign=1789611451150&share_action_id=1fff6fb7-95e8-4c4f-ba97-68a717c03983'
