name: Tanglewood
footer_text: 'Tanglewood Neighborhood Association'
contact_email: indytanglewood@gmail.com
dues_url: 'https://www.paypal.com/qrcodes/managed/250f1e68-c4a0-42d6-a0c6-76b1653a984f'
facebook_url: 'https://facebook.com/'
